import manifest from "../../fixtures/compiler-corpus/coverage-manifest.json";
import vectors from "../../fixtures/compiler-corpus/function-vectors.json";

export type RuntimeStatus = "implemented" | "tracked";
export type CertificationStatus = "unverified" | "certified" | "non_equivalent";

export interface FuncionQlikRegistrada {
  id: string;
  name: string;
  category: string;
  docs: string;
  strategy: string;
  signatureFamily: string;
  deterministic: boolean;
  requiredVectors: string[];
  runtimeStatus: RuntimeStatus;
  certificationStatus: CertificationStatus;
}

const IMPLEMENTED = new Set([
  "acos",
  "acosh",
  "addmonths",
  "addyears",
  "age",
  "alt",
  "applymap",
  "argb",
  "asin",
  "asinh",
  "atan",
  "atan2",
  "atanh",
  "autonumber",
  "avg",
  "bitcount",
  "blackandschole",
  "capitalize",
  "ceil",
  "chi2test_chi2",
  "chi2test_df",
  "chi2test_sig",
  "chr",
  "class",
  "coalesce",
  "combin",
  "correl",
  "cos",
  "cosh",
  "count",
  "countregex",
  "countregexi",
  "date",
  "date#",
  "day",
  "dayend",
  "daynumberofquarter",
  "daynumberofyear",
  "daystart",
  "div",
  "dual",
  "e",
  "emptyisnull",
  "even",
  "exists",
  "exp",
  "extractregex",
  "extractregexgroup",
  "extractregexgroupi",
  "extractregexi",
  "fabs",
  "fact",
  "false",
  "fieldname",
  "fieldno",
  "fieldnumber",
  "filebasename",
  "filedir",
  "fileextension",
  "filename",
  "filepath",
  "filesize",
  "filetime",
  "findoneof",
  "firstsortedvalue",
  "firstvalue",
  "firstworkdate",
  "floor",
  "fmod",
  "frac",
  "fractile",
  "fractileexc",
  "fv",
  "geogetboundingbox",
  "geomakepoint",
  "geopolygon",
  "gmt",
  "hour",
  "hsl",
  "if",
  "inday",
  "index",
  "indexregex",
  "indexregexgroup",
  "indexregexgroupi",
  "indexregexi",
  "inmonths",
  "interval",
  "interval#",
  "inyeartodate",
  "irr",
  "isjson",
  "isnull",
  "isnum",
  "isregex",
  "isregexi",
  "istext",
  "iterno",
  "jsonget",
  "jsonset",
  "keepchar",
  "lastvalue",
  "lastworkdate",
  "left",
  "len",
  "levenshteindist",
  "linest_b",
  "linest_df",
  "linest_f",
  "linest_m",
  "linest_r2",
  "linest_seb",
  "linest_sem",
  "linest_ssreg",
  "linest_ssresid",
  "log",
  "log10",
  "logest_b",
  "logest_df",
  "logest_f",
  "logest_m",
  "logest_r2",
  "logest_seb",
  "logest_sem",
  "logest_ssreg",
  "logest_ssresid",
  "lower",
  "ltrim",
  "makedate",
  "maketime",
  "makeweekdate",
  "mapsubstring",
  "match",
  "matchregex",
  "matchregexi",
  "max",
  "maxstring",
  "mid",
  "min",
  "minstring",
  "minute",
  "missingcount",
  "mod",
  "mode",
  "money",
  "money#",
  "month",
  "monthend",
  "monthname",
  "monthsend",
  "monthsstart",
  "monthstart",
  "networkdays",
  "nooffields",
  "noofrows",
  "nooftables",
  "now",
  "nper",
  "npv",
  "null",
  "nullcount",
  "num",
  "num#",
  "numericcount",
  "odd",
  "only",
  "ord",
  "peek",
  "permut",
  "pi",
  "pick",
  "pmt",
  "pow",
  "previous",
  "purgechar",
  "pv",
  "quarter",
  "quarterend",
  "quartername",
  "quarterstart",
  "qvdcreatetime",
  "qvdfieldname",
  "qvdnooffields",
  "qvdnoofrecords",
  "qvdtablename",
  "rand",
  "rangeavg",
  "rangecount",
  "rangefractile",
  "rangefractileexc",
  "rangeirr",
  "rangemax",
  "rangemaxstring",
  "rangemin",
  "rangeminstring",
  "rangemissingcount",
  "rangemode",
  "rangenpv",
  "rangenullcount",
  "rangenumericcount",
  "rangeonly",
  "rangesum",
  "rangetextcount",
  "rangexirr",
  "rangexnpv",
  "rate",
  "recno",
  "repeat",
  "replace",
  "replaceregex",
  "replaceregexgroup",
  "replaceregexgroupi",
  "replaceregexi",
  "rgb",
  "right",
  "round",
  "rowno",
  "rtrim",
  "second",
  "setdateyearmonth",
  "sign",
  "sin",
  "sinh",
  "sqr",
  "sqrt",
  "stdev",
  "sterr",
  "steyx",
  "subfield",
  "subfieldregex",
  "subfieldregexi",
  "substringcount",
  "sum",
  "tablename",
  "tableno",
  "tablenumber",
  "tan",
  "tanh",
  "text",
  "textbetween",
  "textcount",
  "time",
  "time#",
  "timestamp",
  "timestamp#",
  "today",
  "trim",
  "true",
  "ttest_1t",
  "ttest_1w",
  "ttest_2t",
  "ttest_2w",
  "ttest_df",
  "ttest_dif",
  "ttest_f",
  "ttest_lower",
  "ttest_paired",
  "ttest_pairedw",
  "ttest_sig",
  "ttest_sterr",
  "ttest_upper",
  "upper",
  "utc",
  "week",
  "weekday",
  "weekend",
  "weekname",
  "weekstart",
  "weekyear",
  "xirr",
  "xnpv",
  "year",
  "yearend",
  "yearname",
  "yearstart",
  "ztest_dif",
  "ztest_lower",
  "ztest_sig",
  "ztest_sterr",
  "ztest_upper",
  "ztest_z",
]);

const NON_DETERMINISTIC = new Set([
  "now",
  "today",
  "localtime",
  "gmt",
  "utc",
  "rand",
  "reloadtime",
]);

const vectorsByKey = new Map(
  vectors.functions.map((entry) => [
    `${entry.name.toLowerCase()}::${entry.category}`,
    entry.vectors,
  ]),
);

function signatureFamily(category: string): string {
  const value = category.toLowerCase();
  if (value.includes("aggregation")) return "aggregation";
  if (value.includes("date") || value.includes("time")) return "temporal";
  if (value.includes("string")) return "string";
  if (value.includes("numeric") || value.includes("math")) return "numeric";
  if (value.includes("null") || value.includes("conditional")) return "logical";
  if (value.includes("file")) return "external_file";
  if (value.includes("system")) return "environment";
  if (value.includes("mapping")) return "mapping";
  if (value.includes("inter-record") || value.includes("counter"))
    return "stateful";
  return "specialized";
}

const official = manifest.entries.filter(
  (entry) => entry.surface === "qlik_function",
);

export const REGISTRO_FUNCIONES_QLIK: FuncionQlikRegistrada[] = official.map(
  (entry) => {
    const key = `${entry.name.toLowerCase()}::${entry.family ?? ""}`;
    const runtimeStatus: RuntimeStatus = IMPLEMENTED.has(
      entry.name.toLowerCase(),
    )
      ? "implemented"
      : "tracked";
    return {
      id: entry.id,
      name: entry.name,
      category: entry.family ?? "unknown",
      docs: entry.docs,
      strategy: entry.strategy,
      signatureFamily: signatureFamily(entry.family ?? "unknown"),
      deterministic: !NON_DETERMINISTIC.has(entry.name.toLowerCase()),
      requiredVectors: vectorsByKey.get(key) ?? [
        "normal",
        "null",
        "empty",
        "boundary",
        "type_coercion",
      ],
      runtimeStatus,
      certificationStatus: "unverified",
    };
  },
);

const byName = new Map<string, FuncionQlikRegistrada[]>();
for (const entry of REGISTRO_FUNCIONES_QLIK) {
  const key = entry.name.toLowerCase();
  byName.set(key, [...(byName.get(key) ?? []), entry]);
}

export function obtenerFuncionesQlik(name: string): FuncionQlikRegistrada[] {
  return byName.get(name.toLowerCase()) ?? [];
}

export function obtenerFuncionQlik(
  name: string,
): FuncionQlikRegistrada | undefined {
  return obtenerFuncionesQlik(name)[0];
}
